#!/usr/bin/env bash

SCRIPTPATH="$( cd "$(dirname "$0")" || exit ; pwd -P )"

#set background
if [ -x "$(command -v feh)" ]; then
  feh --bg-scale "$SCRIPTPATH"/down.jpg
fi

leftwm-command "UnloadTheme"

pkill emacs
pkill conky
pkill picom
pkill polybar
#pkill nm-applet
#pkill deja-dup

