#!/usr/bin/env bash
export SCRIPTPATH="$( cd "$(dirname "$0")"  || exit; pwd -P )"

#down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

# my config changes
picom --experimental-backends --config /home/bobossler/.config/picom/picom.conf &
/usr/bin/emacs --daemon &
#flatpak run --command=/app/libexec/deja-dup/deja-dup-monitor org.gnome.DejaDup 

# start conky
conky -c /home/bobossler/.config/conky/leftwm/doom-one-01.conkyrc &

#set the theme.ron config
leftwm-command "LoadTheme $SCRIPTPATH/theme.ron"

#set background
if [ -x "$(command -v feh)" ]; then
  feh --bg-scale --randomize ~/.wallpapers/*
fi

index=0
leftwm-state -q -n -t "$SCRIPTPATH"/sizes.liquid | sed -r '/^\s*$/d' | while read -r width
do
  barname="mainbar$index"
  monitor="$(polybar -m | awk -v i="$(( index + 1))" 'NR==i{print}' | sed 's/:.*//' | tr -d '\n')"
  monitor=$monitor width=$(( width - 16 )) polybar -c $SCRIPTPATH/polybar.config $barname &
  index=$((index+1))
done

